
version: "3.7"
services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - "27017"

  app:
    image: app:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    expose:
      - "5000"
